### ISSUE TITLE
Error - Uncaught Not yet supported

### ISSUE THREAD

**Issue by p32929** [sudhakar3697/node-clipboard-event#1]
I was trying to use this library using https://github.com/WilianZilv/reactron ( React + Electron ). Here's the code that I tried:

```
import React from 'react';
import Grid from "@material-ui/core/Grid";
import {useOvermind} from "../Others/OvermindHelper";
import {on, startListening} from 'clipboard-event'
import Button from "@material-ui/core/Button";

const sl = () => {
    startListening()
    console.log("Clipboard Listening")
    on('change', () => {
        console.log('Clipboard changed');
    });
}

const Clipboard = () => {
    const {state, actions} = useOvermind()

    return (
        <Grid>
            <Button variant='contained' color='primary' onClick={() => {
                sl()
            }}>START</Button>
        </Grid>
    );
};

export default Clipboard;

```

but it shows these errors: 
![Screenshot (51)](https://user-images.githubusercontent.com/6418354/84900287-b1705480-b0cb-11ea-956f-b5760b6351f8.png)
![Screenshot (52)](https://user-images.githubusercontent.com/6418354/84900294-b33a1800-b0cb-11ea-804a-7271e6c2a446.png)

Any solution?
Thanks...

**Comment by sudhakar3697** [comment]
@p32929  Kindly if the 'nodeIntegration' is enabled in your electron config

**Comment by p32929** [comment]
Yes, I just enabled and tried it again. Still the same errors

**Comment by sudhakar3697** [comment]
@p32929  Can you to post the output of process.platform from that file?

**Comment by p32929** [comment]
It outputs "win32"

**Comment by p32929** [comment]
Tried separately and it works fine. But I'm trying to use it inside ElectronJS

**Comment by p32929** [comment]
If you have time, would you give it a try using this ( https://github.com/p32929/reactron-p32929 ) or this ( https://github.com/WilianZilv/reactron ) and share the source code here?
Thanks

**Comment by sudhakar3697** [comment]
@p32929 I tried. I am able to access node in public/index.html but not in components inside the src directory. Kindly check with the author of reactron on accessing node in the components inside the src directory.
