### ISSUE TITLE
WM_CLIPBOARDUPDATE event may be triggered multiple times for a single cut action on Windows

### ISSUE THREAD

**Issue by zivshek** [sudhakar3697/node-clipboard-event#2]

**Comment by v151** [comment]
Seems like it's by design (https://stackoverflow.com/questions/10373713/clipboard-listener-event-is-being-called-twice)

**Comment by sudhakar3697** [comment]
Thanks for reporting. Seems like it's by design (https://stackoverflow.com/questions/10373713/clipboard-listener-event-is-being-called-twice)
