### ISSUE TITLE
Clipboard change not being detected [Ubuntu 22]

### ISSUE THREAD

**Issue by pTinosq** [sudhakar3697/node-clipboard-event#20]
Nothing happens when copying text even though I have copied the example from the repo.

OS: Ubuntu 22.04.2
Node version: 16.16.0

Code:
```
const cL = require("clipboard-event");

console.log("Running"); // THIS RUNS
cL.startListening();
cL.on("change", () => {
    console.log("Test") // NEVER RUNS
}
console.log(cL); // Shows ClipboardEventListener object with evensCount: 1 (so event has registered correctly)
```

**Comment by pTinosq** [comment]
This works thank you! Is there any way to prevent this from happening every time I install the module?

**Comment by anereganaELH** [comment]
Hi, I am in Ubuntu 22.04 and my Electron app is not detecting clipboard changes. Permissions are set to 777 for
node_modules/clipboard-event/platform/clipboard-event-handler-linux. 

When I execute the command
./node_modules/clipboard-event/platform/clipboard-event-handler-linux
 by in terminal clipboard changes are detected. 

I see this error when running the Electron app, I do not know if it affects somehow to clipboard-event:
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
