### ISSUE TITLE
Seperate Listeners for cut,copy and paste

### ISSUE THREAD

**Issue by rayavarapuvikram1** [sudhakar3697/node-clipboard-event#5]
Is it possible to create separate Listeners for cut,copy and paste? Something like this

`clipboardListener.on('cut', () => {
          // When text is cut
    });`
`clipboardListener.on('copy', () => {
        // When text is copied
    });`
`clipboardListener.on('paste', () => {
        // When text is pasted
    });`

**Comment by sudhakar3697** [comment]
Hi,

I have tried finding ways to distinguish the change type. Unfortunately, didn't find any solution. Kindly refer me if you have any samples.

Thank you.
