### ISSUE TITLE
The file that is executed does not have execute permission

### ISSUE THREAD

**Issue by Adithya31101** [sudhakar3697/node-clipboard-event#6]
Was using this package while developing on a Linux (Ubuntu) machine, but apparently, the package was not working as intended, after going through the source, and found out that the system was not able to execute the Linux file named 'clipboard-event-handler-linux' which is an executable I suppose. And this was happening because the file did not have execute permission. 

To give permission to the file: 
`$ chmod u+x <PROGRAM_DIRECTORY>/node_modules/clipboard-event/platform/clipboard-event-handler-linux`

Also, my flavor of ubuntu apparently does not use xclip for clipboard based events so had to run `sudo apt install xclip`

Anywho, got it running, Just wrote this for reference is case anyone is having a hard time!
Cheers!

**Comment by sudhakar3697** [comment]
Thank you @Adithya31101 :)
