### ISSUE TITLE
Detect clipboard content

### ISSUE THREAD

**Issue by AnonHexo** [sudhakar3697/node-clipboard-event#7]
Is there any way to get the clipboard content like:
```js
const clipboardListener = require('clipboard-event');
clipboardListener.startListening();
clipboardListener.on('change', (content) => {
    console.log('Clipboard changed, content: ' + content);
});
clipboardListener.stopListening();
```

**Comment by sudhakar3697** [comment]
Hi,

Currently, there is no param for the data. Kindly use any other module (like [clipboardy)](https://www.npmjs.com/package/clipboardy) to read the clipboard.

Thank you.
