### ISSUE TITLE
How do we access changed clipboard data?

### ISSUE THREAD

**Issue by akash07k** [sudhakar3697/node-clipboard-event#8]
Hey bro,
First of all thanks a lot for this amazing module.
Actually I'm working on a clipboard manager and I want to take some action when user copies some text to the clipboard. However, I'm unable to find the detail/implementation that how to access the clipboard data/text in 
clipboardListener.on("change", () => {
}

here, there's no parameter for the data.
Please help

**Comment by sudhakar3697** [comment]
Hi,

Currently, there is no param for the data. Kindly use any other module (like [clipboardy)](https://www.npmjs.com/package/clipboardy) to read the clipboard.

Thank you.

**Comment by akash07k** [comment]
Ok, thanks a lot.
> Hi,
> 
> Currently, there is no param for the data. Kindly use any other module (like [clipboardy)](https://www.npmjs.com/package/clipboardy) to read the clipboard.
> 
> Thank you.
