### ISSUE TITLE
clipboard-event module spawns a hidden/invisible window incorrectly

### ISSUE THREAD

**Issue by akash07k** [sudhakar3697/node-clipboard-event#9]
Hi @sudhakar3697 
I'm using your clipboard-event module in my electron and so far it is grate.
However, I'm observing that if I use this module and when my app launches, the focus first lands to my app and then an invisible window spawns with the title of clipboard-event-handler-win32.
This hidden/invisible window steals our focus from the application which is not good for the users.
If we unknowingly press alt+f4 on that window, the clipboard events in our app stops working.
Can you help here? I guess some executable is getting launched for capturing the clipboard which is spawning the invisible window.
Can you do something to hide that window?
(I'm on Windows)
(I'm targetting keyboard users mainly with this app)

**Comment by sudhakar3697** [comment]
@akash07k If possible, Pls post the code snippet that you tried?. I can verify from my system.

**Comment by akash07k** [comment]
@sudhakar3697 
Nothing special, the issue persists with simple usage too:
const { clipboard } = require("electron");
const clipboardListener = require("clipboard-event");
clipboardListener.startListening();
clipboardListener.on("change", () => {
        const clipElement = document.getElementById("test");
    clipElement.innerText = `Clipboard is changed with text: ${clipboard.readText()}`;
console.log(`Clipboard is changed with text: ${clipboard.readText()}`);
    });

**Comment by sudhakar3697** [comment]
@akash07k 

Are you trying from the main process or renderer process of electron?.

**Comment by akash07k** [comment]
I've tried from both, renderer process and main process. same issue exists.

**Comment by sudhakar3697** [comment]
It's working fine for me with Electron 10.1.5. I placed it in main.js, preload.js & renderer.js and tried also.

**Comment by akash07k** [comment]
Oh. sadly not working fine for me on electron 13. I guess I'll have to
create my own clipboard module using TCP sockets now.
